# Training configuration for BreastDet

dataset:
  name: CSAW
  splits_dir: /data/tommyngu/BMammo/Detection/Data/AJCAI25/dataset
  max_size: 640

model:
  #MODEL_NAME: facebook/detr-resnet-50
  model_name: hustvl/yolos-base

data:
  train_dir: train
  val_dir: val
  test_dir: test
  batch_size: 8
  num_workers: 4
  image_size: 512

training:
  output_dir: ../tmp
  epochs: 30
  batch_size: 8
  learning_rate: 0.0001
  weight_decay: 0.0005
  warmup_ratio: 0.05
  lr_scheduler_type: cosine_with_restarts
  lr_scheduler_kwargs:
    num_cycles: 1
  eval_do_concat_batches: false
  evaluation_strategy: epoch
  save_strategy: epoch
  save_total_limit: 1
  logging_strategy: epoch
  load_best_model_at_end: true
  metric_for_best_model: eval_map_50
  greater_is_better: true
  dataloader_num_workers: 4
  gradient_accumulation_steps: 2
  remove_unused_columns: False

logging:
  use_wandb: true
  wandb_project: MammoMix
  log_interval: 10

seed: 42

wandb:
  wandb_dir: ../wandb
