# Training configuration for BreastDet with Deformable DETR

dataset:
  name: CSAW
  splits_dir: ../dataset
  max_size: 800

model:
  model_name: SenseTime/deformable-detr

data:
  train_dir: train
  val_dir: val
  test_dir: test
  batch_size: 1  # Minimum batch size để tránh OOM
  num_workers: 0  # Disable multiprocessing để tránh conflicts
  image_size: 800

training:
  output_dir: ../tmp
  epochs: 50  # Giảm epochs để test trước
  batch_size: 1
  learning_rate: 0.0005  # Tăng learning rate để học nhanh hơn
  weight_decay: 0.00001  # Giảm weight decay
  warmup_ratio: 0.1  # Tăng warmup để ổn định
  lr_scheduler_type: cosine  # Cosine scheduler thường tốt hơn cho detection
  eval_do_concat_batches: false
  evaluation_strategy: steps
  eval_steps: 50  # Evaluate thường xuyên hơn
  save_strategy: steps
  save_steps: 50
  save_total_limit: 2
  logging_strategy: steps
  logging_steps: 10  # Log thường xuyên để monitor
  load_best_model_at_end: true
  metric_for_best_model: eval_map_50
  greater_is_better: true
  dataloader_num_workers: 0
  gradient_accumulation_steps: 32  # Rất cao để compensate batch size = 1
  remove_unused_columns: false
  fp16: false  # Disable FP16 để stability
  gradient_checkpointing: false
  max_grad_norm: 5.0  # Tăng để tránh gradient explosion

  # Thêm các setting để suppress warnings và improve stability
  ignore_data_skip: true
  push_to_hub: false
  hub_model_id: null
  hub_strategy: "every_save"
  hub_token: null
  hub_private_repo: false

  # Loss và optimization settings
  label_smoothing_factor: 0.0  # Disable label smoothing cho detection
  optim: "adamw_torch"  # Explicit optimizer

  # Data loading settings
  dataloader_drop_last: false
  dataloader_pin_memory: false

logging:
  use_wandb: false  # Disable wandb để focus vào training
  wandb_project: MammoMix_DeformableDETR
  log_interval: 5

seed: 42

wandb:
  wandb_dir: ../wandb

# Environment settings để suppress warnings
environment:
  suppress_warnings: true
  pytorch_warnings: false
  transformers_warnings: false

# Model loading settings
model_loading:
  low_cpu_mem_usage: true
  torch_dtype: "auto"
  device_map: null
  trust_remote_code: false
  revision: "main"
  use_safetensors: true
