# Training configuration for BreastDet with Deformable DETR

dataset:
  name: CSAW
  splits_dir: ../dataset
  max_size: 800

model:
  model_name: SenseTime/deformable-detr

data:
  train_dir: train
  val_dir: val
  test_dir: test
  batch_size: 2  # Even smaller batch size
  num_workers: 2
  image_size: 800

training:
  output_dir: ../tmp
  epochs: 100  # Much more epochs for convergence
  batch_size: 2
  learning_rate: 0.0002  # Higher learning rate
  weight_decay: 0.0001
  warmup_ratio: 0.05  # Shorter warmup
  lr_scheduler_type: linear  # Simple linear scheduler
  eval_do_concat_batches: false
  evaluation_strategy: epoch
  save_strategy: epoch
  save_total_limit: 3
  logging_strategy: steps
  logging_steps: 25  # More frequent logging
  load_best_model_at_end: true
  metric_for_best_model: eval_map_50
  greater_is_better: true
  dataloader_num_workers: 2
  gradient_accumulation_steps: 16  # Much higher accumulation for effective batch size 32
  remove_unused_columns: false
  fp16: true
  gradient_checkpointing: false  # Disable for stability
  max_grad_norm: 1.0  # Higher gradient clipping

  # Additional training stability settings
  label_smoothing_factor: 0.1
  prediction_loss_only: false
  greater_is_better: true
  metric_for_best_model: eval_map_50

  # Early stopping to prevent overfitting
  early_stopping_patience: 15
  early_stopping_threshold: 0.001

logging:
  use_wandb: true
  wandb_project: MammoMix_DeformableDETR
  log_interval: 5

seed: 42

wandb:
  wandb_dir: ../wandb

# Specific settings to help with learning
optimizer:
  type: AdamW
  lr: 0.0002
  weight_decay: 0.0001
  betas: [0.9, 0.999]
  eps: 1e-8

# Loss function weights (if supported)
loss_weights:
  bbox_loss_coef: 5.0  # Higher weight for bbox regression
  giou_loss_coef: 2.0  # Higher weight for GIoU loss
  class_loss_coef: 1.0  # Standard weight for classification
